-- Create user with password from environment variable
CREATE USER ${POSTGRES_USER} WITH PASSWORD '${POSTGRES_PASSWORD}';
ALTER USER ${POSTGRES_USER} WITH SUPERUSER;

-- Create database
CREATE DATABASE ${POSTGRES_DB};

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};
ALTER DATABASE ${POSTGRES_DB} OWNER TO ${POSTGRES_USER};

-- Create extension for UUID support
CREATE EXTENSION IF NOT EXISTS "uuid-ossp"; 